chore: refactor entrypoint with flags

diff --git a/init.d/etc/fss-proxy.d/.helpers/functions b/init.d/etc/fss-proxy.d/.helpers/functions
--- a/init.d/etc/fss-proxy.d/.helpers/functions
+++ b/init.d/etc/fss-proxy.d/.helpers/functions
@@ -1,6 +1,7 @@
 # vim: set ft=sh fdm=marker ts=2 sw=2 sts=2 tw=85 et:
 # by @allex_wang
 
+# In Alpine, tput is not included in the base package. `apk add --no-cache ncurses`
 BOLD="$(tput bold 2>/dev/null || echo '')"
 GREY="$(tput setaf 0 2>/dev/null || echo '')"
 UNDERLINE="$(tput smul 2>/dev/null || echo '')"
@@ -12,34 +13,12 @@ MAGENTA="$(tput setaf 5 2>/dev/null || echo '')"
 CYAN="$(tput setaf 6 2>/dev/null || echo '')"
 NO_COLOR="$(tput sgr0 2>/dev/null || echo '')"
 
-info() {
-  printf "${BOLD}${CYAN}>${NO_COLOR} %s\n" "$*"
-}
-
-warn() {
-  printf "${YELLOW}! %s${NO_COLOR}\n" "$*"
-}
-
-error() {
-  printf "${RED}x %s${NO_COLOR}\n" "$*" >&2
-}
-
-success() {
-  printf "${GREEN}✓${NO_COLOR} %s\n" "$*"
-}
-
-die() {
-  [ "${1-}" ] && error "fatal: ${1}"
-  exit "${2-1}"
-}
-
-xcp () {
-  local source target dir
-  source=$1
-  target=$2
-  dir="$(dirname "$target")"
-  mkdir -p "$dir" && cp -af "$source" "$target"
-}
+info() { printf "${BOLD}${CYAN}>${NO_COLOR} %s\n" "$*" >&3; }
+warn() { printf "${YELLOW}! %s${NO_COLOR}\n" "$*" >&3; }
+error() { printf "${RED}x %s${NO_COLOR}\n" "$*" >&2; }
+success() { printf "${GREEN}✓${NO_COLOR} %s\n" "$*" >&3; }
+die() { [ "${1-}" ] && error "fatal: ${1}"; exit "${2-1}"; }
+log() { echo >&3 "$@"; }
 
 relative_path () {
   local common path up
@@ -49,5 +28,28 @@ relative_path () {
   done
   path=${up-}${path#"$common"/}; path=${path%/};
   printf %s "${path:-.}"
+}
+
+is_true() {
+  case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
+    true|1|on|yes|y)
+      return 0
+      ;;
+    *)
+      return 1
+      ;;
+  esac
+}
+
+has () {
+  type "${1:?command required}" >/dev/null 2>&1
+}
+
+xcp () {
+  local source target dir
+  source=$1
+  target=$2
+  dir="$(dirname "$target")"
+  mkdir -p "$dir" && cp -af "$source" "$target"
 }
 
